/*
 * This source file was generated by the Gradle 'init' task
 */

package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        final WebPageParser parser = new WebPageParser();
        final WebCrawler crawler = new WebCrawler(parser);
        crawler.run("https://crawlme.monzo.com/");
    }
}

